Resources:
  WebSocketTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.secrets.dynamodb_table_management_connection, 'web-sockets-connections-management'}
      AttributeDefinitions:
        - AttributeName: connectionId
          AttributeType: S
      KeySchema:
        - AttributeName: connectionId
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST