Resources:
  menuHubOnNetworkHubActionDLQ:
    Type: "AWS::SQS::Queue"
    Properties:
      QueueName: "menuHubOnNetworkHubActionDLQ.fifo"
      FifoQueue: true
  menuHubOnNetworkHubActionQueue:
    Type: "AWS::SQS::Queue"
    Properties:
      QueueName: "menuHubOnNetworkHubActionQueue.fifo"
      FifoQueue: true
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt menuHubOnNetworkHubActionDLQ.Arn
        maxReceiveCount: 3
  menuHubOnNetworkHubActionSNSSubscription:
    Type: "AWS::SNS::Subscription"
    Properties:
      TopicArn: !Ref ServiceNetworkHubTopic
      Endpoint: !GetAtt menuHubOnNetworkHubActionQueue.Arn
      Protocol: sqs
      FilterPolicy:
        eventName:
          - "HUB_CREATED"
          - "HUB_UPDATED"
          - "HUB_DELETED"
          - "HUB_DEACTIVATED"
      RawMessageDelivery: "true"
      Region: !Sub us-east-1
  menuHubOnNetworkHubActionQueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: "Allow SNS publish to SQS"
            Effect: Allow
            Principal:
              Service: "sns.amazonaws.com"
            Resource: !GetAtt menuHubOnNetworkHubActionQueue.Arn
            Action:
              - SQS:SendMessage
              - SQS:SendMessageBatch
            Condition:
              ArnEquals:
                aws:SourceArn: !Ref ServiceNetworkHubTopic
      Queues:
        - Ref: menuHubOnNetworkHubActionQueue

Outputs:
  menuHubOnNetworkHubActionQueueArn:
    Value: !GetAtt menuHubOnNetworkHubActionQueue.Arn
    Export:
      Name: ${self:provider.stage}-ext-menuHubOnNetworkHubActionQueue
