export enum ORDER_EVENT {
  CREATED = "ORDER_CREATED",
  UPDATED = "ORDER_UPDATED",
  DELETED = "ORDER_DELETED",
  CONFIRMED = "ORDER_CONFIRMED",
  DELIVERED = "ORDER_DELIVERED"
}

export enum PROGRAM_EVENT {
  CREATED = "PROGRAM_CREATED",
  UPDATED = "PROGRAM_UPDATED",
  DELETED = "PROGRAM_DELETED",
  STATUS_CHANGED = "HOTEL_STATUS_CHANGED",
}

export enum CODE_EVENT {
  CREATED = "CODE_CREATED",
  DELETED = "CODE_DELETED",
  BULK_CREATED = "CODE_BULK_CREATED",
  BULK_DELETED = "CODE_BULK_DELETED",
}

export enum HUB_EVENT {
  CREATED = "HUB_CREATED",
  UPDATED = "HUB_UPDATED",
  OMS_CREATED = "OMS_CREATED",
  OMS_UPDATED = "OMS_UPDATED",
  DELETED = "HUB_DELETED",
  DEACTIVATED = "HUB_DEACTIVATED",
  CREATED_ADAPTER = "HUB_CREATED_ADAPTER",
}

export enum HOTEL_EVENT {
  CREATED = "HOTEL_CREATED",
  UPDATED = "HOTEL_UPDATED",
  OMS_CREATED = "OMS_HOTEL_CREATED",
  OMS_UPDATED = "OMS_HOTEL_UPDATED",
  DELETED = "HOTEL_DELETED",
  UPDATED_INTEGRATION_CONFIGS_SHUTTLE_APP = "UPDATED_INTEGRATION_CONFIGS_SHUTTLE_APP",
  UPDATED_INTEGRATION_CONFIGS_PMS = "UPDATED_INTEGRATION_CONFIGS_PMS",
  UPDATED_INTEGRATION_CONFIGS_ACTIVITIES_APP = "UPDATED_INTEGRATION_CONFIGS_ACTIVITIES_APP",
  UPDATED_INTEGRATION_CONFIGS_MENU_APP = "UPDATED_INTEGRATION_CONFIGS_MENU_APP",
  UPDATED_INTEGRATION_CONFIGS_VOUCHERS_APP = "UPDATED_INTEGRATION_CONFIGS_VOUCHERS_APP",
  UPDATED_PAYMENT_SETTINGS = "UPDATED_PAYMENT_SETTINGS",
  STATUS_CHANGED = "HOTEL_STATUS_CHANGED",
  MENU_ASSIGNED = "HOTEL_MENU_ASSIGNED",
  CREATED_ADAPTER = "HOTEL_CREATED_ADAPTER",
}

export enum CITY_EVENT {
  CREATED = "CITY_CREATED",
  UPDATED = "CITY_UPDATED",
  DELETED = "CITY_DELETED",
}

export enum MENU_EVENT {
  CREATED = "MENU_CREATED",
  UPDATED = "MENU_UPDATED",
  DELETED = "MENU_DELETED",
  HOTELS_ASSIGNED = "MENU_HOTELS_ASSIGNED",
}

export enum MODIFIER_EVENT {
  CREATED = "MODIFIER_CREATED",
  UPDATED = "MODIFIER_UPDATED",
  DELETED = "MODIFIER_DELETED",
}

export enum CATEGORY_EVENT {
  CREATED = "CATEGORY_CREATED",
  UPDATED = "CATEGORY_UPDATED",
  DELETED = "CATEGORY_DELETED",
  CREATED_ADAPTER = "CATEGORY_CREATED_ADAPTER",
}

export enum LABEL_EVENT {
  CREATED = "LABEL_CREATED",
  UPDATED = "LABEL_UPDATED",
  DELETED = "LABEL_DELETED",
  CREATED_ADAPTER = "LABEL_CREATED_ADAPTER",
}

export enum PRODUCT_EVENT {
  CREATED = "PRODUCT_CREATED",
  UPDATED = "PRODUCT_UPDATED",
  DELETED = "PRODUCT_DELETED",
  MODIFIER_UPDATED = "PRODUCT_MODIFIER_UPDATED",
  OUT_OF_STOCK = "PRODUCT_OUT_OF_STOCK",
  BACK_IN_STOCK = "PRODUCT_BACK_IN_STOCK",
  STATUS_CHANGED = "PRODUCT_STATUS_CHANGED",
}

export enum USER_EVENT {
  CREATED = "USER_CREATED",
  UPDATED = "USER_UPDATED",
  DELETED = "USER_DELETED",
  CREATED_ADAPTER = "USER_CREATED_ADAPTER"
}
